Updated Community Section
sristy17/Codess-Hackathon pull request #6
Opened 2024-08-22 16:52 UTC by jasmineanand

**Summary:**
Provide a brief overview of the changes introduced in this PR.

**Changes Made:**
Describe the changes you made and why they were necessary.

**Testing Performed:**
Explain how you tested your changes to ensure they work as expected.

**Related Issues:**
Link any related issues or tickets that this PR addresses.

**Additional Notes:**
Any additional information or context about this PR.

2024-08-22 17:50 UTC, sristy17 requested changes
[Screencast from 2024-08-22 23-19-22.webm](https://github.com/user-attachments/assets/be86bda4-5dfe-4ed1-ae90-2ea3057e4c7b)


Please fix this issue.

2024-08-22 18:16 UTC, sristy17 requested changes

2024-08-22 18:16 UTC, sristy17 commented on views/pages/community.ejs
>      <link rel="stylesheet" href="../../public/css/style.css">
Change this to style_community.css

2024-08-24 13:07 UTC, jasmineanand commented on views/pages/community.ejs
>      <link rel="stylesheet" href="../../public/css/style.css">
yeah done

2024-08-24 15:00 UTC, jasmineanand commented
Hi @sristy17 , could you please review and approve this PR when you get a chance? We need your approval to proceed with the merge. Thanks!

2024-08-24 15:35 UTC, merged